// Export video course APIs
export {
  studentVideoCourseApiSlice,
  useGetAvailableVideoCoursesQuery,
  useGetVideoCourseByIdQuery,
  useGetFeaturedVideoCoursesQuery,
  useGetPopularVideoCoursesQuery,
  useSearchVideoCoursesQuery,
  useEnrollInVideoCourseMutation,
  useGetMyVideoEnrollmentsQuery,
  useGetVideoCourseEnrollmentQuery,
  useGetVideoCourseProgressQuery,
  useUpdateVideoProgressMutation,
  useMarkChapterCompleteMutation,
  useGetVideoCourseSectionsQuery,
  useGetSectionChaptersQuery,
  useGetChapterDetailQuery,
  useGetCourseNotesQuery,
  useCreateNoteMutation,
  useUpdateNoteMutation,
  useDeleteNoteMutation,
  useGetCourseBookmarksQuery,
  useCreateBookmarkMutation,
  useDeleteBookmarkMutation,
  useGetCourseReviewsQuery,
  useCreateCourseReviewMutation,
  useUpdateCourseReviewMutation,
  useDeleteCourseReviewMutation,
  useGetMyCertificatesQuery,
  useGetCourseCertificateQuery,
  useGenerateCertificateMutation,
  useGetCourseRecommendationsQuery,
  useGetStudentVideoAnalyticsQuery,
  useUpdateLearningGoalsMutation,
  useGetWishlistQuery,
  useAddToWishlistMutation,
  useRemoveFromWishlistMutation,
} from './video-courses';

export type {
  StudentVideoCourse,
  CourseEnrollment,
  StudentCourseProgress,
  VideoProgressUpdate,
  ChapterCompletion,
  CourseEnrollmentRequest,
  CourseSearchParams,
  CourseReview,
  CreateReviewData,
  StudentVideoAnalytics,
  CourseCertificate,
  CourseRecommendation,
  StudentNote,
  StudentBookmark,
} from './video-courses';

// Export practice course APIs
export {
  studentPracticeApiSlice,
  useGetAvailableCoursesQuery as useGetAvailablePracticeCoursesQuery,
  useGetCourseDetailQuery as useGetPracticeCourseDetailQuery,
  useGetStudentProgressQuery,
  useSelectActiveCourseMutation,
  useUpdateProgressMutation,
  useGetHeartsStatusQuery,
  useUseHeartMutation,
  useRefillHeartsMutation,
  useGetCourseUnitsWithProgressQuery,
  useGetLessonDetailQuery,
  useGetLessonProgressQuery,
  useSubmitChallengeMutation,
  useStartLearningSessionMutation,
  useEndLearningSessionMutation,
  useGetStudentAchievementsQuery,
  useGetStudyStreakQuery,
  useGetLeaderboardQuery,
  useGetPracticeRecommendationsQuery,
  useGetStudentAnalyticsQuery,
  useGetWeakSkillsQuery,
  useMarkLessonCompletedMutation,
  useFollowUserMutation,
  useUnfollowUserMutation,
} from './practice-courses';

export type {
  StudentCourse,
  StudentUserProgress,
  LessonDetail,
  ChallengeSubmission,
  ChallengeResult,
  CourseSelectionData,
  ProgressUpdateData,
  CourseUnitsWithProgress,
  HeartsSystem,
  HeartAction,
  StudentLeaderboard,
  StudyStreak,
  PracticeRecommendation,
  StudentAnalytics,
  LearningSession,
  SessionSummary,
  StudentAchievement,
} from './practice-courses';