// Export video course APIs
export {
  teacherVideoCourseApiSlice,
  useGetAllTeacherCoursesQuery,
  useGetTeacherCourseByIdQuery as useGetTeacherVideoCourseByIdQuery,
  useCreateTeacherVideoCourseMutation,
  useUpdateTeacherVideoCourseMutation,
  useDeleteTeacherVideoCourseMutation,
  useGetCourseSectionsQuery,
  useCreateCourseSectionMutation,
  useUpdateCourseSectionMutation,
  useDeleteCourseSectionMutation,
  useGetSectionChaptersQuery,
  useCreateChapterMutation,
  useUpdateChapterMutation,
  useDeleteChapterMutation,
  useGetVideoUploadUrlMutation,
  useGetVideoCourseAnalyticsQuery,
  useGetVideoEnrollmentsQuery,
  usePublishVideoCourseMutation,
} from './video-courses';

export type {
  TeacherVideoCourse,
  CreateVideoCourseData,
  UpdateVideoCourseData,
  CourseSection,
  CreateSectionData,
  UpdateSectionData,
  CreateChapterData,
  UpdateChapterData,
  VideoUploadRequest,
  VideoUploadResponse,
  VideoCourseAnalytics,
  StudentVideoProgress,
} from './video-courses';

// Export practice course APIs
export {
  teacherPracticeApiSlice,
  useGetTeacherCoursesQuery as useGetTeacherPracticeCoursesQuery,
  useGetTeacherCoursesQuery as useGetLaboratoryCoursesQuery, // Legacy compatibility
  useGetPracticeCourseByIdQuery,
  useCreateTeacherCourseMutation,
  useUpdatePracticeCourseMutation,
  useDeleteTeacherCourseMutation,
  usePublishTeacherCourseMutation,
  useGetCourseUnitsQuery,
  useCreateTeacherUnitMutation,
  useUpdateTeacherUnitMutation,
  useDeleteTeacherUnitMutation,
  useGetUnitLessonsQuery,
  useCreateTeacherLessonMutation,
  useUpdateTeacherLessonMutation,
  useDeleteTeacherLessonMutation,
  useGetLessonChallengesQuery,
  useCreateTeacherChallengeMutation,
  useUpdateTeacherChallengeMutation,
  useDeleteTeacherChallengeMutation,
  useGetCourseAnalyticsQuery,
  useGetStudentProgressListQuery,
  useGetTeacherDashboardQuery,
  useGetAudioUploadUrlMutation,
  useGetImageUploadUrlMutation,
  useUpdateChallengeOptionMutation,
  useValidateTranslationWithAIMutation,
  useGenerateTranslationSuggestionsMutation,
} from './practice-courses';

export type {
  TeacherCourse,
  CreateCourseData,
  UpdateCourseData,
  TeacherUnit,
  CreateUnitData,
  UpdateUnitData,
  TeacherLesson,
  CreateLessonData,
  UpdateLessonData,
  TeacherChallenge,
  CreateChallengeData,
  UpdateChallengeData,
  CourseAnalytics,
  StudentProgressDetail,
  TeacherDashboardStats,
  UploadUrlResponse,
  FileUploadRequest,
  AITranslationValidation,
  AITranslationSuggestions,
  AIValidationResponse,
  AISuggestionResponse,
} from './practice-courses';